import os

STORAGE_CONNECTION_STRING = os.environ.get("AZURE_STORAGE_CONNECTION_STRING", None)
TABLE_NAME = os.environ.get("TABLE_NAME", None)
COSMOSDB_ENDPOINT = os.environ.get("COSMOSDB_ENDPOINT", None)
COSMOSDB_PRIMARYKEY = os.environ.get("COSMOSDB_PRIMARYKEY", None)
COSMOSDB_DATABASE = 'opa'
ACR_LOGINSERVER = os.environ.get("ACR_LOGINSERVER", None)
ACR_USERNAME = os.environ.get("ACR_USERNAME", None)
ACR_PASSWORD = os.environ.get("ACR_PASSWORD", None)
ACR_BUNDLE_ARTIFACT_SHA = os.environ.get("ACR_BUNDLE_ARTIFACT_SHA", None)
BUNDLE_TAR = os.environ.get("BUNDLE_TAR", None)
IS_EMULATED = False