version: '3.7'

services:
  # Bootstrap the database and run all migrations
  kong-migrations:
    build: ..
    command: ["kong", "migrations", "bootstrap"]
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
    restart: on-failure

  # Kong instance
  kong:
    build: ..
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: postgres
      KONG_LOG_LEVEL: debug
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
      # add kong-plugin-opa to the list of plugins that come bundled with Kong
      KONG_PLUGINS: bundled,opa
    ports:
      - "8000-8001:8000-8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    restart: on-failure

  # Kong database
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong

  # Open Policy Agent as a server
  opa:
    image: openpolicyagent/opa:latest
    command: "run --server --log-level debug"
    ports:
      - "8181:8181"
