{
 "title": "OPA Metrics",
 "description": "Open Policy Agents Runtime metrics",
 "tags": [
  "go",
  "golang",
  "opa"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(go_goroutines, namespace)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(go_goroutines{namespace=\"$namespace\",  container=~\"opa\"}, instance)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Avg Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{instance=~\"$instance\", namespace=\"$namespace\"}[$interval])) / sum(rate(http_request_duration_seconds_count{instance=~\"$instance\", namespace=\"$namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\", namespace=\"$namespace\"}[$interval])) by (le))",
     "legendFormat": "50th Quantile (Median)"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\", namespace=\"$namespace\"}[$interval])) by (le))",
     "legendFormat": "90th Quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\", namespace=\"$namespace\"}[$interval])) by (le))",
     "legendFormat": "95th Quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\", namespace=\"$namespace\"}[$interval])) by (le))",
     "legendFormat": "99th Quantile"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{instance}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Bundles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Bundle Loaded Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(bundle_loaded_counter{namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bundle tracker",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "last_bundle_request{namespace=~\"$namespace\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "last_success_bundle_activation{namespace=~\"$namespace\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "last_success_bundle_download{namespace=~\"$namespace\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "last_success_bundle_request{namespace=~\"$namespace\", instance=~\"$instance\"} > 0"
    }
   ]
  },
  {
   "title": "Bundle Loading Duration (nanosec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(bundle_loading_duration_ns_sum{namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} {{name}} {{stage}}"
    }
   ]
  },
  {
   "title": "Plugins Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "plugin_status_gauge{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bundle Failed Load",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "increase(bundle_failed_load_counter{namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object and Pointers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences per $interval",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{namespace=\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{namespace=\"$namespace\", instance=~\"$instance\"} - go_memstats_frees_total{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated Per $interval",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{namespace=\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation per $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory In Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes obtained from system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes allocated & still in-use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes waiting to be used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_idle_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes in use ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes released to OS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_released_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Objects allocated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Memory Off-heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Mspan bytes usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes used for mspan obtained from system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes used for mcache obtained from system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes in use by mcache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes used for garbage collection system metadata",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes used by the profiling bucket hash table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes when next garbage collection will take place",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes used for other system allocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{instance}}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}