version: '2'
services:
  opa:
    image: openpolicyagent/opa:0.4.8
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "io.directory.users:/users.json"
      - "io.vcs.contributors:/contributors.json"
      # Authorization policies.
      - "display.rego"
      - "pull.rego"
      - "sudo_authz.rego"
      - "sshd_authz.rego"
    volumes:
      - ./policy/users.json:/users.json
      - ./policy/contributors.json:/contributors.json
      # Authorization policies.
      - ./policy/display.rego:/display.rego
      - ./policy/pull.rego:/pull.rego
      - ./policy/sudo_authz.rego:/sudo_authz.rego
      - ./policy/sshd_authz.rego:/sshd_authz.rego

  frontend:
    image: openpolicyagent/demo-pam
    ports:
      - "2222:22"
    volumes:
      - ./etc/frontend_host_id:/etc/host_identity.json

  backend:
    image: openpolicyagent/demo-pam
    ports:
      - "2223:22"
    volumes:
      - ./etc/backend_host_id:/etc/host_identity.json
