version: '2'
services:
  opa:
    image: openpolicyagent/opa:0.4.8
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "ssh.rego"
      - "sudo.rego"
      - "io.directory.users:/users.json"
      - "io.vcs.contributors:/contributors.json"
    volumes:
      - ./policy/ssh.rego:/ssh.rego
      - ./policy/sudo.rego:/sudo.rego
      - ./policy/users.json:/users.json
      - ./policy/contributors.json:/contributors.json

  webapp:
    image: openpolicyagent/demo-pam
    ports:
      - "2222:22"
    volumes:
      - ./etc/webapp_host_id:/etc/host_identity.json

  backend:
    image: openpolicyagent/demo-pam
    ports:
      - "2223:22"
    volumes:
      - ./etc/backend_host_id:/etc/host_identity.json
