kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ${pwd}/api-server
    containerPath: /etc/kubernetes/api-server
- role: worker
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraVolumes:
    - name: api-server
      hostPath: /etc/kubernetes/api-server
      mountPath: /etc/kubernetes/api-server
    extraArgs:
      authorization-mode: Node,RBAC,Webhook
      authorization-webhook-version: v1
      authorization-webhook-config-file: /etc/kubernetes/api-server/authz-webhook.yaml
      feature-gates: "EphemeralContainers=true"
